#!/usr/bin/env ruby
# encoding: UTF-8
# exe/hulaki

$:.unshift File.expand_path("../../lib", __FILE__)

require 'hulaki'
begin
  cli_options = ARGV.clone
  config = Hulaki::OptionParser.new.parse(ARGV)
  Hulaki::Core.new(config).perform
rescue OptionParser::InvalidOption
  $stderr.puts "The option `#{cli_options.join(' ')}` is "\
              "not valid. see `hulaki -l` for more info".red
end
