#!/usr/bin/env ruby
# encoding: UTF-8
# exe/hulaki
this_file = Pathname.new(__FILE__).realpath

$:.unshift File.expand_path("../../lib", this_file)

require 'hulaki'
binding.pry
config = Hulaki::OptionParser.new.parse(ARGV)
Hulaki::Core.new(config).perform
